name             'drupal-env'
maintainer       'Sergiu Ionescu'
maintainer_email 'sergiu.ionescu@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures drupal-env'
long_description 'Installs/Configures drupal-env'
version          '0.1.1'

depends 'lamp', '~> 0.2.0'
depends 'drush', '~> 0.1.0'
depends 'database', '~> 2.3.0'
depends 'php'
depends 'cron', '~> 1.4.0'
