name             'drupal'
maintainer       'Sergiu Ionescu'
maintainer_email 'sergiu.ionescu@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures drupal'
long_description 'Installs/Configures drupal'
version          '1.0.0'

depends 'lamp'
depends 'drush'
depends 'mysql2_chef_gem'
depends 'database'
